import { LotterySet, Seller, WeeklySchedule, DailyStationConfig } from './types';

export const INITIAL_LOTTERY_SETS: LotterySet[] = [
  { "id": "00", "numbers": ["00", "12", "24", "36", "48", "51", "63", "75", "87", "99"] },
  { "id": "01", "numbers": ["01", "13", "25", "37", "49", "52", "64", "76", "88", "90"] },
  { "id": "02", "numbers": ["02", "14", "26", "38", "40", "53", "65", "77", "89", "91"] },
  { "id": "03", "numbers": ["03", "15", "27", "39", "41", "54", "66", "78", "80", "92"] },
  { "id": "04", "numbers": ["04", "16", "28", "30", "42", "55", "67", "79", "81", "93"] },
  { "id": "05", "numbers": ["05", "17", "29", "31", "43", "56", "68", "70", "82", "94"] },
  { "id": "06", "numbers": ["06", "18", "20", "32", "44", "57", "69", "71", "83", "95"] },
  { "id": "07", "numbers": ["07", "19", "21", "33", "45", "58", "60", "72", "84", "96"] },
  { "id": "08", "numbers": ["08", "10", "22", "34", "46", "59", "61", "73", "85", "97"] },
  { "id": "09", "numbers": ["09", "11", "23", "35", "47", "50", "62", "74", "86", "98"] }
];

export const INITIAL_WEEKLY_SCHEDULES: WeeklySchedule[] = [
  { "dayOfWeek": 0, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 1, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 2, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 3, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 4, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 5, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true },
  { "dayOfWeek": 6, "mainStationBaseQuantity": 20640, "subStationBaseQuantities": { "sub1": 10320, "sub2": 10320 }, "isActive": true }
];

export const MAIN_STATION_TICKET_MAP: Record<string, number> = (() => {
  const map: Record<string, number> = {};
  for (let i = 0; i < 100; i++) {
    map[i.toString().padStart(2, '0')] = 192;
  }
  ['02', '14', '26', '38', '40', '53', '65', '77', '89', '91'].forEach(n => map[n] = 256);
  ['08', '10', '22', '34', '46', '59', '61', '73', '85', '97'].forEach(n => map[n] = 272);
  return map;
})();

export const SUB_STATION_TICKET_MAP: Record<string, number> = (() => {
  const map: Record<string, number> = {};
  // 10320 total sheets = 45 numbers with 112 sheets, 55 numbers with 96 sheets
  for (let i = 0; i < 100; i++) {
    const num = i.toString().padStart(2, '0');
    if (i < 45) {
      map[num] = 112; 
    } else {
      map[num] = 96;
    }
  }
  return map;
})();

export const INITIAL_STATION_CONFIGS: DailyStationConfig[] = [
  { "dayOfWeek": 0, "mainStationName": "TG", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] },
  { "dayOfWeek": 1, "mainStationName": "TP 2", "subStations": [ { "id": "sub1", "name": "BẾN TRE" }, { "id": "sub2", "name": "BẠC LIÊU" } ] },
  { "dayOfWeek": 2, "mainStationName": "VT", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] },
  { "dayOfWeek": 3, "mainStationName": "ĐN", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] },
  { "dayOfWeek": 4, "mainStationName": "TN", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] },
  { "dayOfWeek": 5, "mainStationName": "BD", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] },
  { "dayOfWeek": 6, "mainStationName": "TP 7", "subStations": [ { "id": "sub1", "name": "Đài Phụ 1" }, { "id": "sub2", "name": "Đài Phụ 2" } ] }
];

export const INITIAL_SELLERS: Seller[] = [
  { "id": "1", "name": "CHỊ HƯƠNG LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [ { "number": "54", "quantity": 160 }, { "number": "62", "quantity": 160 } ], "manualSetId": "07" },
  { "id": "2", "name": "BÍCH LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": false, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "3", "name": "MƯỜI LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "4", "name": "A TRUNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 176, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "5", "name": "A DẤU LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 448, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "6", "name": "DIỄM LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 288, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "7", "name": "C LOAN LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "8", "name": "ANH DŨNG LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "9", "name": "VỢ DŨNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "10", "name": "ÚT HẰNG LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "11", "name": "C NHÂM LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "12", "name": "HỒNG PHÁT LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 512, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "07" },
  { "id": "13", "name": "C TUYẾN BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 416, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "14", "name": "QUÝ LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 512, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "15", "name": "CHỊ HẠNH LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "16", "name": "ANH 9 LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 272, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "20", "name": "QUÀNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "21", "name": "C VÂN LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 288, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "22", "name": "TÝ LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 192, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "23", "name": "LÀ LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "25", "name": "A TIẾN LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 224, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "26", "name": "THU TS LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 800, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "27", "name": "C LAN LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "28", "name": "A PHONG LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "29", "name": "NGHĨA LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "30", "name": "SỮA XE LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 288, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "31", "name": "THƠM LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 272, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "32", "name": "A QUANG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "33", "name": "PHONG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 96, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "34", "name": "GIÀU LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "35", "name": "A BẠCH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 240, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "07" },
  { "id": "36", "name": "A KHANH LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 240, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "37", "name": "THỌ LN", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "38", "name": "THẢO LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "40", "name": "TÙNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "41", "name": "A XÊ LN", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 544, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "42", "name": "HỒNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "44", "name": "A THẮNG BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 800, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "45", "name": "CHÂU LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "46", "name": "SÂN NHÀ", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 304, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "47", "name": "A THẮNG LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "48", "name": "A LỢI BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "49", "name": "A THÀNH BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 288, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "50", "name": "C THANH BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "51", "name": "HẰNG BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "53", "name": "C PHƯỢNG BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "07" },
  { "id": "54", "name": "C HẢO BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "56", "name": "KIM BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "57", "name": "A CƯỜNG BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "59", "name": "KIẾM BB", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 720, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "60", "name": "C THUỶ BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "61", "name": "C HIỀN BB", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "62", "name": "QUỲNH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "63", "name": "C TÀI BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "65", "name": "LINH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "66", "name": "NGÂN BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "67", "name": "A MINH BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "69", "name": "DÌ 8 BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 288, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "70", "name": "A TUẤT BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "71", "name": "CHÚ 2 BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "07" },
  { "id": "74", "name": "A THẮNG TÓC BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "75", "name": "BÀ 2 BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 224, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "76", "name": "A VUI BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "77", "name": "THUỶ AD BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "78", "name": "A DŨNG BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "79", "name": "TUẤN BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 304, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "80", "name": "C THUẬN BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "81", "name": "A HOAN BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "82", "name": "CHÚ MINH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 304, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "83", "name": "CHỊ ÚT BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 224, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "85", "name": "DUNG M BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "87", "name": "A THANH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "90", "name": "A TỐT BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "93", "name": "A BỬU BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 176, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "94", "name": "MỚI 5 BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 96, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "96", "name": "PHƯỢNG BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "97", "name": "BÍCH RK BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "98", "name": "LỢP LH", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "99", "name": "A TÌNH LH", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "101", "name": "A HẠNH LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 240, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "102", "name": "THỤ LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "108", "name": "MẸ TRANG LH", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" },
  { "id": "109", "name": "TRAI LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 240, "allocationMode": "auto", "currentSetIndex": 2, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "110", "name": "MỌI LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 304, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "08" },
  { "id": "114", "name": "C.LỢI LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 3, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "y76ev45z1", "name": "TRANG LH", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 560, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "t5v4i8cui", "name": "THÚY LH", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "6xsp5mb8f", "name": "C LẦU BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "469bg1p87", "name": "LIÊN LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 416, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "vhhwbjzfi", "name": "C HUẾ LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 320, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "06" },
  { "id": "uf4rlu2ju", "name": "A THÔNG LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 176, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "caqftjgon", "name": "AN LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [ { "number": "10", "quantity": 16 }, { "number": "20", "quantity": 16 }, { "number": "30", "quantity": 16 }, { "number": "40", "quantity": 16 }, { "number": "50", "quantity": 16 }, { "number": "60", "quantity": 16 }, { "number": "70", "quantity": 16 }, { "number": "80", "quantity": 16 }, { "number": "90", "quantity": 16 } ], "manualSetId": "05" },
  { "id": "5xj0ukyyf", "name": "B. PHƯỢNG LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 304, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "90qgblhp8", "name": "THƯ LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 128, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "vdk6nhite", "name": "CHỊ 6 LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 240, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "05" },
  { "id": "ikx9emiog", "name": "C. MƯỜI LH", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "xyzm7m8ov", "name": "GIANG LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "qnfldxp1u", "name": "CẨM LH", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 64, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "yjqud30s8", "name": "ĐAN BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "03" },
  { "id": "0tb63rfev", "name": "ỬNG BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 560, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "6ymhwakmn", "name": "BÔNG", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "nk12i5wx7", "name": "A KÝ BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "qsmjninu6", "name": "TÍM BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "ovimxpkno", "name": "NHƯ BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 256, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "00" },
  { "id": "lur2auxwt", "name": "C LINH BB", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 112, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "v4q7niyrt", "name": "PHƯỚC BB", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 480, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": true, "isEnabled": false, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "6wz77cadm", "name": "C ĐIỆP LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "mw0gl7o3s", "name": "THÚY LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "09" },
  { "id": "9ha0thqky", "name": "TUYẾN LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 400, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "02" },
  { "id": "y8pfwandd", "name": "TÝ 2 LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 160, "allocationMode": "auto", "currentSetIndex": 1, "isAutoMode": true, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "j22uaylzc", "name": "THẢO LN", "setType": "single", "sheetsOption": "16", "targetTotalTickets": 208, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "04" },
  { "id": "dc3qm4a42", "name": "A TĂNG LN", "setType": "double", "sheetsOption": "16", "targetTotalTickets": 728, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": true, "isEnabled": false, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [] },
  { "id": "ahqsoaxz1", "name": "THU LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 640, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "07" },
  { "id": "8tbkgylph", "name": "THỦY LN", "setType": "single", "sheetsOption": "32", "targetTotalTickets": 352, "allocationMode": "auto", "currentSetIndex": 0, "isAutoMode": false, "isEnabled": true, "mainEnabled": true, "subStationRatios": { "sub1": 20, "sub2": 10 }, "customPreferences": [], "manualSetId": "01" }
];
